apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pfgw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0075-tenant/ci10t-776-0075-app/devfile-sample-pfgw@sha256:8b2aca83d7f02afb9cb9e5c79278127b7f40e569a1505b901d007d658ac2eb14
        name: my-nodejs
        resources: {}
status: {}
