apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pfgw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pfgw
    app.kubernetes.io/part-of: ci10t-776-0075-app
  name: devfile-sample-pfgw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pfgw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pfgw
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0075-tenant/ci10t-776-0075-app/devfile-sample-pfgw@sha256:8b2aca83d7f02afb9cb9e5c79278127b7f40e569a1505b901d007d658ac2eb14
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
